name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Build for all platforms
        run: make build-all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/linux-amd64/cvetodo-agent
            dist/windows-amd64/cvetodo-agent.exe
            dist/darwin-amd64/cvetodo-agent 