name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make deps

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/cvetodo-agent ./cmd/agent
          tar -czf dist/packages/cvetodo-agent-${{ github.ref_name }}-linux-amd64.tar.gz -C dist/linux-amd64 cvetodo-agent

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/windows-amd64/cvetodo-agent.exe ./cmd/agent
          cd dist/windows-amd64 && zip -r ../packages/cvetodo-agent-${{ github.ref_name }}-windows-amd64.zip cvetodo-agent.exe

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/darwin-amd64/cvetodo-agent ./cmd/agent
          tar -czf dist/packages/cvetodo-agent-${{ github.ref_name }}-darwin-amd64.tar.gz -C dist/darwin-amd64 cvetodo-agent

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/packages/cvetodo-agent-${{ github.ref_name }}-linux-amd64.tar.gz
            dist/packages/cvetodo-agent-${{ github.ref_name }}-windows-amd64.zip
            dist/packages/cvetodo-agent-${{ github.ref_name }}-darwin-amd64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 