name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make deps

      - name: Build and package
        run: |
          make build-all
          make package
        env:
          VERSION: ${GITHUB_REF#refs/tags/v}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/packages/cvetodo-agent-${{ github.ref_name }}-linux-amd64.tar.gz
            dist/packages/cvetodo-agent-${{ github.ref_name }}-windows-amd64.zip
            dist/packages/cvetodo-agent-${{ github.ref_name }}-darwin-amd64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 